spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  h2:
    console:
    enabled: true
  config:
    activate:
      on-profile: development