---

logging:
  level:
    root: INFO

spring:
  datasource:
#    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false