---

logging:
  level:
    root: INFO

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false