spring:
  application:
    name: app
  jpa:
    show-sql: true
    ## ??? ?????? ? ???????? ??????? ? ????????
    generate-ddl: true
    ## ???????? ?? ?????? ?? ?? ?????? ?????????????? ???????
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development